package ma.fstm.ilisi.gestioncontacts.Model.bo;
// Generated Mar 16, 2022 12:06:56 AM by Hibernate Tools 4.3.1



/**
 * Contacts generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private int id;
     private Type types;
     private String tel;
     private String nom;
     private String prenom;
     private String email;

    public Contact() {
    }

	
    public Contact(int id, Type types) {
        this.id = id;
        this.types = types;
    }
    public Contact(int id, Type types, String tel, String nom, String prenom, String email) {
       this.id = id;
       this.types = types;
       this.tel = tel;
       this.nom = nom;
       this.prenom = prenom;
       this.email = email;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Type getTypes() {
        return this.types;
    }
    
    public void setTypes(Type types) {
        this.types = types;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        return   "type=" + types + ", tel=" + tel + ", nom=" + nom + ", prenom=" + prenom + ", email=" + email;
    }




}


