package ma.fstm.ilisi.gestioncontacts.Model.bo;
// Generated Mar 16, 2022 12:06:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Types generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private String type;
     private Set<Contact> contactses = new HashSet<Contact>();

    public Type() {
    }

	
    public Type(String type) {
        this.type = type;
    }
    public Type(String type, Set contactses) {
       this.type = type;
       this.contactses = contactses;
    }
   
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getContactses() {
        return this.contactses;
    }
    
    public void setContactses(Set contactses) {
        this.contactses = contactses;
    }

    @Override
    public String toString() {
        return type;
    }




}


